services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_API_SECRET=${VITE_API_SECRET}
        - VITE_ENABLE_DEMO_DASHBOARD=${VITE_ENABLE_DEMO_DASHBOARD}
        - VITE_DEFAULT_DOMAIN=${VITE_DEFAULT_DOMAIN}
    container_name: engora_portal
    ports:
      - "9010:80"
    restart: unless-stopped
